name = "DHNetworkSimulator"
uuid = "2eb6275f-2a99-494f-9a8b-24b61cb8f4b7"
version = "0.1.0"
authors = ["Pavel Svoboda <pav.svoboda2000@gmail.com>"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ForwardMethods = "5fe2550f-d27e-4649-9aea-fdf9a83a1aa9"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TSFrames = "9f90e835-9451-4aaa-bcb1-743a1b8d2f84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorSchemes = "3.31.0"
Colors = "0.13.1"
DataStructures = "0.19.3"
Dates = "1.11.0"
ForwardMethods = "1.7.0"
GLMakie = "0.13.8"
GraphMakie = "0.6.3"
Graphs = "1.13.4"
MetaGraphsNext = "0.7.4"
Plots = "1.41.4"
StatsBase = "0.34.10"
TSFrames = "0.2.2"
Test = "1.11.0"
