
[deps]
DHNetworkSimulator = "2eb6275f-2a99-494f-9a8b-24b61cb8f4b7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TSFrames = "9f90e835-9451-4aaa-bcb1-743a1b8d2f84"

[compat]
Dates = "1.11.0"
FileIO = "1.18.0"
GLMakie = "0.13.8"
GraphMakie = "0.6.3"
Graphs = "1.13.4"
Plots = "1.41.5"
TSFrames = "0.2.2"
